[package]
name = "snapmail_proc_macro"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
syn = {version="1.0.70",features=["full","fold"]}
quote = "1.0.9"
